#!/usr/bin/env ruby -w

# syntax:
#   tag_grep scratch.txt todo

require 'date'

def is_datetime(line)
  return false unless line.length == 20
  date, time = line.split(" ")
  is_valid_date = (Date.parse(date) rescue false)
  is_valid_date = is_valid_date && (date.split("-").length == 3)
  return false unless is_valid_date
  is_valid_time = time.split(":").length == 3
  return is_valid_time
end

def is_hashtags(line)
  line[0] == "#"
end

def is_hashtag_match(line, search_tag)
  tags = line.split(" ")
  return tags.any? { |tag| tag == search_tag }
end

def check_and_print_block(is_matched_block, current_block)
  if is_matched_block
    puts current_block.join("")
    puts "-"*100
    puts "\n"
  end
end

# https://www.safaribooksonline.com/library/view/ruby-cookbook/0596523696/ch01s15.html
def wrap(s, width=100)
  s.gsub(/(.{1,#{width}})(\s+|\Z)/, "\\1\n")
end

def my_grep(search_file, search_tag)
  is_matched_block = false
  current_block = []

  File.foreach(search_file).with_index do |line, line_num|
    if line
      if is_datetime(line)
        check_and_print_block(is_matched_block, current_block)
        is_matched_block = false
        current_block = [line, "\n"]
      elsif is_hashtags(line)
        if is_hashtag_match(line, search_tag)
          is_matched_block = true
          current_block.push(line)
        else
          is_matched_block = false
          current_block = []
        end
      else
        if is_matched_block
          current_block.push(wrap(line))
        end
      end
    end
  end
  check_and_print_block(is_matched_block, current_block)
end

my_grep(ARGV[0], "#"+ARGV[1])

